Document: jyut-dict
Title: Debian jyut-dict Manual
Author: <insert document author here>
Abstract: This manual describes what jyut-dict is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jyut-dict/jyut-dict.sgml.gz

Format: postscript
Files: /usr/share/doc/jyut-dict/jyut-dict.ps.gz

Format: text
Files: /usr/share/doc/jyut-dict/jyut-dict.text.gz

Format: HTML
Index: /usr/share/doc/jyut-dict/html/index.html
Files: /usr/share/doc/jyut-dict/html/*.html
