Document: jyutdict
Title: Debian jyutdict Manual
Author: <insert document author here>
Abstract: This manual describes what jyutdict is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jyutdict/jyutdict.sgml.gz

Format: postscript
Files: /usr/share/doc/jyutdict/jyutdict.ps.gz

Format: text
Files: /usr/share/doc/jyutdict/jyutdict.text.gz

Format: HTML
Index: /usr/share/doc/jyutdict/html/index.html
Files: /usr/share/doc/jyutdict/html/*.html
