#ifndef ENTRYPHONETICOPTIONS_H
#define ENTRYPHONETICOPTIONS_H

enum class EntryPhoneticOptions {
    ONLY_JYUTPING,
    ONLY_PINYIN,
    PREFER_JYUTPING,
    PREFER_PINYIN,
};

#endif // ENTRYPHONETICOPTIONS_H
