#ifndef ENTRYCHARACTERSOPTIONS_H
#define ENTRYCHARACTERSOPTIONS_H

enum class EntryCharactersOptions {
    ONLY_SIMPLIFIED,
    ONLY_TRADITIONAL,
    PREFER_SIMPLIFIED,
    PREFER_TRADITIONAL,
};

#endif // ENTRYCHARACTERSOPTIONS_H
