#!/bin/bash

# Zip up entirety of src/jyut-dict into a zip beside jyut-dict
cd ../../../
tar -cvzf ../jyut-dict_1.22.0207.tar.gz * --overwrite

# Switch to src/ directory
cd ../

# Create folder matching current version of jyut-dict
rm -rf jyut-dict_1.22.0207
mkdir jyut-dict_1.22.0207
cd jyut-dict_1.22.0207

# Expand zip file into the folder
tar -xvzf ../jyut-dict_1.22.0207.tar.gz --overwrite

# Delete unneeded files copied by make
rm ./dict.db
rm ./jyut-dict

# Copy files generated by dh_make into the debian folder
cp -r ../jyut-dict/platform/linux/deb/debian ./debian

# Creates an orig tar.gz file required for debuild
# Also creates generic debian/ folder structure if previous command failed
dh_make -c mit -s -f ../jyut-dict_1.22.0207.tar.gz -p jyut-dict_1.22.0207

# Generate the .deb file.
debuild